export enum INELIGIBLE_REASON {
    MERCHANT_NOT_IN_LIST,
    MCC_NOT_IN_LIST,
    BILL_PAYMENT,
    TAX_PAYMENT,
    PAYMENT_METHOD,
    BILL_SIZE_SMALL,
    BILL_SIZE_LARGE,
    BILL_CURRENCY,
    PARTIAL_ONLY,
    DAY_OF_WEEK,
    DAY_OF_MONTH,
    DISQUALIFIED_MERCHANT,
    USER_OPT_OUT
}